{
 "title": "proj",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{node=\"$node\",namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\",pod=\"$pod\"}, container)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$node\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "monitor the number of pods that restarts on the namespace",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "cpu usage namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])))*100",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "the number of pods that running on the namespace",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "the number of deployment  that running on the name space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_created{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "the network traffic of the name space (transmit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (namespace)",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "the network traffic of the name space (receive)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (namespace)",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "memory usage of the name space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{})",
     "legendFormat": "$namespace"
    }
   ]
  },
  { "title": "node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "monitor the number of pods running on the node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{node=~\"$node\"}) by (node)",
     "legendFormat": "$node"
    }
   ]
  },
  {
   "title": "cpu usage by cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance=\"$instance\"}[5m]))",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "cpu usage by %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[1m])) * 100))",
     "legendFormat": "$instance"
    }
   ]
  },
  { "title": "pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "cpu usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\",namespace=\"$namespace\"}[5m])) by (pod_name, container_name)*1000"
    }
   ]
  },
  {
   "title": "cpu usage by %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!~\".*prometheus.*\",namespace=\"$namespace\",pod=\"$pod\"}[5m])) by (pod_name, container_name) /\nsum(container_spec_cpu_quota{name!~\".*prometheus.*\",namespace=\"$namespace\",pod=\"$pod\"}/container_spec_cpu_period{name!~\".*prometheus.*\",namespace=\"$namespace\",pod=\"$pod\"}) by (pod_name, container_name)",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "the disk I/O write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])) by (pod)",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "the disk I/O read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])) by (pod)",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "monitor the network traffic (transmit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])) by (pod)",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "monitor the network traffic (recive)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])) by (pod)",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "the average memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "avg(sum by (pod) (container_memory_usage_bytes{namespace=\"$namespace\", pod=\"$pod\"}))",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "pod age",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - kube_pod_created{namespace=\"$namespace\", pod=\"$pod\"}) / 60",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "monitor the cpu and memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\", container=\"$container\"}[5m])"
      }
     ]
    }
   ]
  }
 ]
}